### PR TITLE
Use project-wide Babel config file

### PR DESCRIPTION
**Pull request by knowler**
## Description

As of Babel 7, `babel.config.js` is the proper file to use for project configuration. `.babelrc.json` et al. also work, however, they are meant to be file-relative.

See: https://babeljs.io/docs/en/config-files#project-wide-configuration

### CODE REVIEW

**Comment by knowler** [comment]
Alternatively, we could use a `babel.config.mjs` file and use ESM syntax rather than CommonJS. We’d need to bump the `engine.node` version in `package.json`. I was going to make a PR to do that anyway since that version doesn’t match the lowest version for Prettier (wants Node 12) and ESLint (wants `^10.12.0` or 12 and greater). Both of those seem to work anyway.

**Comment by JasonTheAdams** [comment]
@knowler We don't need this anymore, right?

**Comment by knowler** [comment]
I don’t think we need it if we put `.react()` in the Laravel Mix config and if we add `browserslist` with the browsers we are supporting to the `package.json` file (since it _should_ affect Babel and Autoprefixer).

**Comment by JasonTheAdams** [comment]
Closing as it's not necessary if we use `.react()` in Laravel Mix.

**Comment by knowler** [comment]
We should just remove the babel config file and add the `browserslist` to `package.json` so we are explicitly defining the list of browsers we are supporting. This way we aren't building for IE 11 when we don't support it.

**Comment by JasonTheAdams** [comment]
Sounds good to me. Make yourself a task to do that in another PR _at a good time_.

**Pull request closed without merging**
